In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('euros_2024_shot_map.csv')

In [3]:
print(type(df['location'][0]))

<class 'str'>

In [4]:
#df_shot = df[df['type']].reset_index(drop=True)

- df['type'] directly selects the 'type' column, which contains strings (like 'Shot').
- Pandas interprets this as trying to select columns whose names are the values in the 'type' column. So, if a row has 'type' as 'Shot', pandas tries to select the column named 'Shot'. This is why you get the KeyError "None of ... 'Shot' ... are in the [columns]". It's looking for a column named 'Shot', not filtering rows where the 'type' column's value is 'Shot'.
- df[boolean_series]: Row selection (filtering).
- df[list_of_column_names]: Column selection.

In [5]:
df_shot = df[df['type'] == 'Shot'].reset_index(drop=True)

In [6]:
df_shot

,50_50,bad_behaviour_card,ball_receipt_outcome,block_deflection,block_save_block,carry_end_location,clearance_aerial_won,clearance_body_part,clearance_head,clearance_left_foot,...,shot_saved_to_post,goalkeeper_success_in_play,ball_recovery_offensive,dribble_no_touch,player_off_permanent,goalkeeper_penalty_saved_to_post,goalkeeper_shot_saved_off_target,shot_follows_dribble,shot_saved_off_target,shot_redirect
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1335,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1336,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1337,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1338,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1339,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
df_shot['type'].notnull()

0       True
1       True
2       True
3       True
4       True
        ...
1335    True
1336    True
1337    True
1338    True
1339    True
Name: type, Length: 1340, dtype: bool

In [8]:
has_nulls = df_shot['type'].isnull().any()  # or .notnull().all() for all non-null
if has_nulls:
    print("The 'type' column has NULL values.")
else:
    print("The 'type' column has NO NULL values.")

The 'type' column has NO NULL values.

In [9]:
mask = df['type'].str.contains('Shot\n', regex=True) 
rows_with_shot_newlines = df[mask]
rows_with_shot_newlines

Empty DataFrame
Columns: [50_50, bad_behaviour_card, ball_receipt_outcome, block_deflection, block_save_block, carry_end_location, clearance_aerial_won, clearance_body_part, clearance_head, clearance_left_foot, clearance_right_foot, counterpress, dribble_outcome, duel_outcome, duel_type, duration, foul_committed_advantage, foul_committed_card, foul_committed_penalty, foul_won_advantage, foul_won_defensive, foul_won_penalty, goalkeeper_body_part, goalkeeper_end_location, goalkeeper_outcome, goalkeeper_position, goalkeeper_punched_out, goalkeeper_technique, goalkeeper_type, id, index, injury_stoppage_in_chain, interception_outcome, location, match_id, minute, off_camera, out, period, play_pattern, player, player_id, position, possession, possession_team, possession_team_id, related_events, second, shot_aerial_won, shot_body_part, shot_deflected, shot_end_location, shot_first_time, shot_freeze_frame, shot_outcome, shot_statsbomb_xg, shot_technique, shot_type, substitution_outcome, substitution_outcome_id, substitution_replacement, substitution_replacement_id, tactics, team, team_id, timestamp, type, under_pressure, ball_recovery_recovery_failure, block_offensive, dribble_nutmeg, dribble_overrun, foul_committed_offensive, shot_one_on_one, clearance_other, foul_committed_type, miscontrol_aerial_won, goalkeeper_shot_saved_to_post, shot_open_goal, shot_saved_to_post, goalkeeper_success_in_play, ball_recovery_offensive, dribble_no_touch, player_off_permanent, goalkeeper_penalty_saved_to_post, goalkeeper_shot_saved_off_target, shot_follows_dribble, shot_saved_off_target, shot_redirect]
Index: []

[0 rows x 89 columns]

In [10]:
unique_values = df['type'].unique()
print("Unique values in 'type' column:", unique_values)

Unique values in 'type' column: ['Shot']

In [11]:
df['type_stripped'] = df['type'].str.strip()
df['type_stripped'].unique()

array(['Shot'], dtype=object)

In [12]:
df.columns

Index(['50_50', 'bad_behaviour_card', 'ball_receipt_outcome',
       'block_deflection', 'block_save_block', 'carry_end_location',
       'clearance_aerial_won', 'clearance_body_part', 'clearance_head',
       'clearance_left_foot', 'clearance_right_foot', 'counterpress',
       'dribble_outcome', 'duel_outcome', 'duel_type', 'duration',
       'foul_committed_advantage', 'foul_committed_card',
       'foul_committed_penalty', 'foul_won_advantage', 'foul_won_defensive',
       'foul_won_penalty', 'goalkeeper_body_part', 'goalkeeper_end_location',
       'goalkeeper_outcome', 'goalkeeper_position', 'goalkeeper_punched_out',
       'goalkeeper_technique', 'goalkeeper_type', 'id', 'index',
       'injury_stoppage_in_chain', 'interception_outcome', 'location',
       'match_id', 'minute', 'off_camera', 'out', 'period', 'play_pattern',
       'player', 'player_id', 'position', 'possession', 'possession_team',
       'possession_team_id', 'related_events', 'second', 'shot_aerial_won',
       'shot_body_part', 'shot_deflected', 'shot_end_location',
       'shot_first_time', 'shot_freeze_frame', 'shot_outcome',
       'shot_statsbomb_xg', 'shot_technique', 'shot_type',
       'substitution_outcome', 'substitution_outcome_id',
       'substitution_replacement', 'substitution_replacement_id', 'tactics',
       'team', 'team_id', 'timestamp', 'type', 'under_pressure',
       'ball_recovery_recovery_failure', 'block_offensive', 'dribble_nutmeg',
       'dribble_overrun', 'foul_committed_offensive', 'shot_one_on_one',
       'clearance_other', 'foul_committed_type', 'miscontrol_aerial_won',
       'goalkeeper_shot_saved_to_post', 'shot_open_goal', 'shot_saved_to_post',
       'goalkeeper_success_in_play', 'ball_recovery_offensive',
       'dribble_no_touch', 'player_off_permanent',
       'goalkeeper_penalty_saved_to_post', 'goalkeeper_shot_saved_off_target',
       'shot_follows_dribble', 'shot_saved_off_target', 'shot_redirect',
       'type_stripped'],
      dtype='object')

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1340 entries, 0 to 1339
Data columns (total 90 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   50_50                             0 non-null      float64
 1   bad_behaviour_card                0 non-null      float64
 2   ball_receipt_outcome              0 non-null      float64
 3   block_deflection                  0 non-null      float64
 4   block_save_block                  0 non-null      float64
 5   carry_end_location                0 non-null      float64
 6   clearance_aerial_won              0 non-null      float64
 7   clearance_body_part               0 non-null      float64
 8   clearance_head                    0 non-null      float64
 9   clearance_left_foot               0 non-null      float64
 10  clearance_right_foot              0 non-null      float64
 11  counterpress                      0 non-null      float64
 12  dribble_outcome                   0 non-null      float64
 13  duel_outcome                      0 non-null      float64
 14  duel_type                         0 non-null      float64
 15  duration                          1340 non-null   float64
 16  foul_committed_advantage          0 non-null      float64
 17  foul_committed_card               0 non-null      float64
 18  foul_committed_penalty            0 non-null      float64
 19  foul_won_advantage                0 non-null      float64
 20  foul_won_defensive                0 non-null      float64
 21  foul_won_penalty                  0 non-null      float64
 22  goalkeeper_body_part              0 non-null      float64
 23  goalkeeper_end_location           0 non-null      float64
 24  goalkeeper_outcome                0 non-null      float64
 25  goalkeeper_position               0 non-null      float64
 26  goalkeeper_punched_out            0 non-null      float64
 27  goalkeeper_technique              0 non-null      float64
 28  goalkeeper_type                   0 non-null      float64
 29  id                                1340 non-null   object
 30  index                             1340 non-null   int64
 31  injury_stoppage_in_chain          0 non-null      float64
 32  interception_outcome              0 non-null      float64
 33  location                          1340 non-null   object
 34  match_id                          1340 non-null   int64
 35  minute                            1340 non-null   int64
 36  off_camera                        3 non-null      object
 37  out                               25 non-null     object
 38  period                            1340 non-null   int64
 39  play_pattern                      1340 non-null   object
 40  player                            1340 non-null   object
 41  player_id                         1340 non-null   float64
 42  position                          1340 non-null   object
 43  possession                        1340 non-null   int64
 44  possession_team                   1340 non-null   object
 45  possession_team_id                1340 non-null   int64
 46  related_events                    1340 non-null   object
 47  second                            1340 non-null   int64
 48  shot_aerial_won                   133 non-null    object
 49  shot_body_part                    1340 non-null   object
 50  shot_deflected                    35 non-null     object
 51  shot_end_location                 1340 non-null   object
 52  shot_first_time                   380 non-null    object
 53  shot_freeze_frame                 1305 non-null   object
 54  shot_outcome                      1340 non-null   object
 55  shot_statsbomb_xg                 1340 non-null   float64
 56  shot_technique                    1340 non-null   object
 57  shot_type                         1340 non-null   object
 58  substitution_outcome              0 non-null      float64
 59  substitution_outcome_id           0 non-null      float64
 60  substitution_replacement          0 non-null      float64
 61  substitution_replacement_id       0 non-null      float64
 62  tactics                           0 non-null      float64
 63  team                              1340 non-null   object
 64  team_id                           1340 non-null   int64
 65  timestamp                         1340 non-null   object
 66  type                              1340 non-null   object
 67  under_pressure                    387 non-null    object
 68  ball_recovery_recovery_failure    0 non-null      float64
 69  block_offensive                   0 non-null      float64
 70  dribble_nutmeg                    0 non-null      float64
 71  dribble_overrun                   0 non-null      float64
 72  foul_committed_offensive          0 non-null      float64
 73  shot_one_on_one                   53 non-null     object
 74  clearance_other                   0 non-null      float64
 75  foul_committed_type               0 non-null      float64
 76  miscontrol_aerial_won             0 non-null      float64
 77  goalkeeper_shot_saved_to_post     0 non-null      float64
 78  shot_open_goal                    9 non-null      object
 79  shot_saved_to_post                5 non-null      object
 80  goalkeeper_success_in_play        0 non-null      float64
 81  ball_recovery_offensive           0 non-null      float64
 82  dribble_no_touch                  0 non-null      float64
 83  player_off_permanent              0 non-null      float64
 84  goalkeeper_penalty_saved_to_post  0 non-null      float64
 85  goalkeeper_shot_saved_off_target  0 non-null      float64
 86  shot_follows_dribble              1 non-null      object
 87  shot_saved_off_target             4 non-null      object
 88  shot_redirect                     1 non-null      object
 89  type_stripped                     1340 non-null   object
dtypes: float64(53), int64(8), object(29)
memory usage: 942.3+ KB

In [14]:
for column in df.columns: 
    if df[column].count() <= 53: # .count() returns the number of non-NA/null observations 
        df.drop(column, axis=1, inplace=True)

In [15]:
df

,duration,id,index,location,match_id,minute,period,play_pattern,player,player_id,...,shot_outcome,shot_statsbomb_xg,shot_technique,shot_type,team,team_id,timestamp,type,under_pressure,type_stripped
0,0.865482,e0159fb4-47e8-422e-9216-6e44cf173408,342,"[99.6, 51.2]",3942819,6,1,Regular Play,Xavi Simons,39167.0,...,Goal,0.048935,Normal,Open Play,Netherlands,941,00:06:41.445,Shot,NaN,Shot
1,0.935472,0ec0210f-4dfb-4a1d-ab52-4c1f2156b219,446,"[88.2, 36.6]",3942819,12,1,Regular Play,Harry Kane,10955.0,...,Saved,0.028932,Normal,Open Play,England,768,00:12:39.772,Shot,NaN,Shot
2,0.083512,825afa97-dac6-4d4b-b16d-585361c9ff61,496,"[104.5, 41.6]",3942819,13,1,From Throw In,Bukayo Saka,22084.0,...,Blocked,0.071750,Normal,Open Play,England,768,00:13:41.900,Shot,NaN,Shot
3,0.404925,edf7aa7b-0c91-451b-b980-b4dc582aa0b1,505,"[108.1, 40.0]",3942819,17,1,Other,Harry Kane,10955.0,...,Goal,0.783500,Normal,Penalty,England,768,00:17:34.626,Shot,NaN,Shot
4,0.163705,f4db1f38-035c-49df-acc3-e8f237e266c5,665,"[117.0, 47.6]",3942819,22,1,Regular Play,Phil Foden,4354.0,...,Saved,0.188995,Normal,Open Play,England,768,00:22:28.596,Shot,NaN,Shot
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1335,0.999611,2be33cb2-8c4a-472f-8e1b-471ba899fdbf,2911,"[102.8, 25.6]",3930158,79,2,From Corner,Maximilian Mittelstädt,12407.0,...,Off T,0.021256,Half Volley,Open Play,Germany,770,00:34:23.870,Shot,NaN,Shot
1336,0.890694,defe8eb9-a518-4385-aca4-b33556d27463,3007,"[98.9, 55.4]",3930158,82,2,Regular Play,Leroy Sané,3053.0,...,Saved,0.026379,Normal,Open Play,Germany,770,00:37:53.489,Shot,True,Shot
1337,0.891476,39107e2c-b6b5-490b-a5e1-b55296af1202,3083,"[92.6, 43.3]",3930158,85,2,From Counter,Leroy Sané,3053.0,...,Off T,0.030833,Normal,Open Play,Germany,770,00:40:11.694,Shot,NaN,Shot
1338,0.296845,1759ff23-09e4-4170-8a38-90f97cea79e9,3097,"[108.8, 50.0]",3930158,86,2,From Free Kick,Scott McKenna,10002.0,...,Wayward,0.060526,Normal,Open Play,Scotland,942,00:41:31.319,Shot,True,Shot
1339,0.123032,6ed1aa99-3539-41d1-9dcd-27badaa5e837,3369,"[98.5, 39.4]",3930158,92,2,Regular Play,Emre Can,3493.0,...,Goal,0.049994,Normal,Open Play,Germany,770,00:47:32.605,Shot,True,Shot

In [16]:
print(type(df['location'][0]))

<class 'str'>

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1340 entries, 0 to 1339
Data columns (total 31 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   duration            1340 non-null   float64
 1   id                  1340 non-null   object
 2   index               1340 non-null   int64
 3   location            1340 non-null   object
 4   match_id            1340 non-null   int64
 5   minute              1340 non-null   int64
 6   period              1340 non-null   int64
 7   play_pattern        1340 non-null   object
 8   player              1340 non-null   object
 9   player_id           1340 non-null   float64
 10  position            1340 non-null   object
 11  possession          1340 non-null   int64
 12  possession_team     1340 non-null   object
 13  possession_team_id  1340 non-null   int64
 14  related_events      1340 non-null   object
 15  second              1340 non-null   int64
 16  shot_aerial_won     133 non-null    object
 17  shot_body_part      1340 non-null   object
 18  shot_end_location   1340 non-null   object
 19  shot_first_time     380 non-null    object
 20  shot_freeze_frame   1305 non-null   object
 21  shot_outcome        1340 non-null   object
 22  shot_statsbomb_xg   1340 non-null   float64
 23  shot_technique      1340 non-null   object
 24  shot_type           1340 non-null   object
 25  team                1340 non-null   object
 26  team_id             1340 non-null   int64
 27  timestamp           1340 non-null   object
 28  type                1340 non-null   object
 29  under_pressure      387 non-null    object
 30  type_stripped       1340 non-null   object
dtypes: float64(3), int64(8), object(20)
memory usage: 324.7+ KB

In [18]:
# ascending order of the probability for goal shots.
goal_shots_df = df[
    (df['type'] == 'Shot') & (df['shot_outcome'] == 'Goal')
][['team', 'player', 'shot_statsbomb_xg']].sort_values(
    by='shot_statsbomb_xg',
    ascending=True
)

# Print the resulting DataFrame
goal_shots_df

             team                         player  shot_statsbomb_xg
1264     Slovenia                     Erik Janža           0.012828
902        Turkey                     Arda Güler           0.018738
155       Denmark                Morten Hjulmand           0.019366
1011      Romania           Răzvan Gabriel Marin           0.019968
45          Spain    Lamine Yamal Nasraoui Ebana           0.026812
...           ...                            ...                ...
204   Switzerland                Xherdan Shaqiri           0.783500
203       England                    Bukayo Saka           0.783500
202   Switzerland             Fabian Lukas Schär           0.783500
1151     Portugal  Bruno Miguel Borges Fernandes           0.851883
1014      Romania             Denis Mihai Drăguş           0.883042

[126 rows x 3 columns]

In [19]:
# Group the data by `team` and `player` to count shots and goals.
# It is assumed that 'Goal' is the value for a successful shot in the 'shot_outcome' column.
player_stats = df.groupby(['team', 'player']).agg(
    total_shot=('shot_outcome', 'count'),  # Count total shots
    total_goals=('shot_outcome', lambda x: (x == 'Goal').sum())  # Count total goals
).reset_index()

# Calculate the percentage of goals to total shots.
player_stats['percentage_of_goal/shot'] = (player_stats['total_goals'] / player_stats['total_shot']) * 100

# Format the percentage to have two decimal places.
player_stats['percentage_of_goal/shot'] = player_stats['percentage_of_goal/shot'].round(2)

# Sort the data by the number of total shots in descending order.
sorted_stats = player_stats.sort_values(by='total_goals', ascending=False)

# Rename columns for clarity and select the final columns.
final_df = sorted_stats[['team', 'player', 'total_shot', 'total_goals', 'percentage_of_goal/shot']].rename(columns={
    'total_shot': 'Total Shot',
    'total_goals': 'Total_Goal',
    'percentage_of_goal/shot': 'Percentage of Goal/Shot'
})

# Display the final sorted dataframe.
final_df.head(20)

,team,player,Total Shot,Total_Goal,Percentage of Goal/Shot
195,Portugal,Bernardo Mota Veiga de Carvalho e Silva,9,3,33.33
112,Georgia,Georges Mikautadze,6,3,50.00
165,Netherlands,Cody Mathès Gakpo,13,3,23.08
276,Spain,Daniel Olmo Carvajal,17,3,17.65
84,England,Harry Kane,18,3,16.67
87,England,Jude Bellingham,7,3,42.86
248,Slovakia,Ivan Schranz,5,3,60.00
127,Germany,Jamal Musiala,10,3,30.00
196,Portugal,Bruno Miguel Borges Fernandes,11,2,18.18
225,Romania,Răzvan Gabriel Marin,6,2,33.33
316,Turkey,Merih Demiral,3,2,66.67
126,Germany,Florian Wirtz,8,2,25.00
81,England,Cole Palmer,4,2,50.00
80,England,Bukayo Saka,9,2,22.22
278,Spain,Fabián Ruiz Peña,17,2,11.76
130,Germany,Kai Havertz,19,2,10.53
167,Netherlands,Donyell Malen,6,2,33.33
291,Switzerland,Breel-Donald Embolo,8,2,25.00
306,Switzerland,Xherdan Shaqiri,3,2,66.67
286,Spain,Nicholas Williams Arthuer,12,2,16.67

In [5]:
df.to_csv('euro24_shot_map.csv', index=False)